### ISSUE TITLE
crash when make with -j option

### ISSUE THREAD

**Issue by minhyuk** [rizsotto/Bear#87]
Hi, 
Recently I decided to use bear in my project. 
As you already know, I could hooked the compilation db from Android build successfully.
But there is one problem left which is when I try android build with <b>make -j4</b>, libear crashed with:
<pre>
admin@ubuntu:~/minhyuk/open_source/zlib$ bear make -j4
...
..<skip>...
...

*** glibc detected *** make: munmap_chunk(): invalid pointer: 0x0000000000fc9a60 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7db26)[0x7ff47a192b26]
make[0x40df59]
make[0x40fbb1]
make[0x410390]
make[0x4190a2]
make[0x419433]
make[0x4183f7]
make[0x419433]
make[0x4183f7]
make[0x419433]
make[0x4183f7]
make[0x419433]
make[0x4183f7]
make[0x4198b7]
make[0x403d88]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed)[0x7ff47a13676d]
make[0x403fb1]
======= Memory map: ========
00400000-00428000 r-xp 00000000 08:01 1835670                            /usr/bin/make
00627000-00628000 r--p 00027000 08:01 1835670                            /usr/bin/make
00628000-0062a000 rw-p 00028000 08:01 1835670                            /usr/bin/make
00fa3000-00fe5000 rw-p 00000000 00:00 0                                  [heap]
7ff4793fa000-7ff47940f000 r-xp 00000000 08:01 2101128                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ff47940f000-7ff47960e000 ---p 00015000 08:01 2101128                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ff47960e000-7ff47960f000 r--p 00014000 08:01 2101128                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ff47960f000-7ff479610000 rw-p 00015000 08:01 2101128                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ff479610000-7ff479cf4000 r--p 00000000 08:01 1841598                    /usr/lib/locale/locale-archive
7ff479cf4000-7ff479d0c000 r-xp 00000000 08:01 2102095                    /lib/x86_64-linux-gnu/libpthread-2.15.so
7ff479d0c000-7ff479f0b000 ---p 00018000 08:01 2102095                    /lib/x86_64-linux-gnu/libpthread-2.15.so
7ff479f0b000-7ff479f0c000 r--p 00017000 08:01 2102095                    /lib/x86_64-linux-gnu/libpthread-2.15.so
7ff479f0c000-7ff479f0d000 rw-p 00018000 08:01 2102095                    /lib/x86_64-linux-gnu/libpthread-2.15.so
7ff479f0d000-7ff479f11000 rw-p 00000000 00:00 0 
7ff479f11000-7ff479f13000 r-xp 00000000 08:01 2102108                    /lib/x86_64-linux-gnu/libdl-2.15.so
7ff479f13000-7ff47a113000 ---p 00002000 08:01 2102108                    /lib/x86_64-linux-gnu/libdl-2.15.so
7ff47a113000-7ff47a114000 r--p 00002000 08:01 2102108                    /lib/x86_64-linux-gnu/libdl-2.15.so
7ff47a114000-7ff47a115000 rw-p 00003000 08:01 2102108                    /lib/x86_64-linux-gnu/libdl-2.15.so
7ff47a115000-7ff47a2c9000 r-xp 00000000 08:01 2102104                    /lib/x86_64-linux-gnu/libc-2.15.so
7ff47a2c9000-7ff47a4c8000 ---p 001b4000 08:01 2102104                    /lib/x86_64-linux-gnu/libc-2.15.so
7ff47a4c8000-7ff47a4cc000 r--p 001b3000 08:01 2102104                    /lib/x86_64-linux-gnu/libc-2.15.so
7ff47a4cc000-7ff47a4ce000 rw-p 001b7000 08:01 2102104                    /lib/x86_64-linux-gnu/libc-2.15.so
7ff47a4ce000-7ff47a4d3000 rw-p 00000000 00:00 0 
7ff47a4d3000-7ff47a4da000 r-xp 00000000 08:01 2102098                    /lib/x86_64-linux-gnu/librt-2.15.so
7ff47a4da000-7ff47a6d9000 ---p 00007000 08:01 2102098                    /lib/x86_64-linux-gnu/librt-2.15.so
7ff47a6d9000-7ff47a6da000 r--p 00006000 08:01 2102098                    /lib/x86_64-linux-gnu/librt-2.15.so
7ff47a6da000-7ff47a6db000 rw-p 00007000 08:01 2102098                    /lib/x86_64-linux-gnu/librt-2.15.so
7ff47a6db000-7ff47a6de000 r-xp 00000000 08:01 1855068                    /usr/lib/libcsbuild.so
7ff47a6de000-7ff47a8dd000 ---p 00003000 08:01 1855068                    /usr/lib/libcsbuild.so
7ff47a8dd000-7ff47a8de000 r--p 00002000 08:01 1855068                    /usr/lib/libcsbuild.so
7ff47a8de000-7ff47a8df000 rw-p 00003000 08:01 1855068                    /usr/lib/libcsbuild.so
7ff47a8df000-7ff47a901000 r-xp 00000000 08:01 2102097                    /lib/x86_64-linux-gnu/ld-2.15.so
7ff47aae6000-7ff47aaea000 rw-p 00000000 00:00 0 
7ff47aafd000-7ff47ab01000 rw-p 00000000 00:00 0 
7ff47ab01000-7ff47ab02000 r--p 00022000 08:01 2102097                    /lib/x86_64-linux-gnu/ld-2.15.so
7ff47ab02000-7ff47ab04000 rw-p 00023000 08:01 2102097                    /lib/x86_64-linux-gnu/ld-2.15.so
7ffe48d37000-7ffe48d58000 rw-p 00000000 00:00 0                          [stack]
7ffe48de1000-7ffe48de3000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
admin@ubuntu:~/minhyuk/open_source/zlib$ bear: fopen: No such file or directory
bear: fopen: No such file or directory
</pre>
you can reproduce this issue by zlib build.

I am not expert in this area, but It seems like synchronization issue so far. 
I observed this issue carefully and I found one suspect which is when bear try to env capture - restore - release sequence may not act synchronized way.

What do you think?

**Comment by rizsotto** [comment]
thanks @minhyuk for the report. could you tell me which version of Bear are you using?

**Comment by minhyuk** [comment]
Hi, 
I use modified version of bear, but you can reproduced by master branch, I confirmed.
If you can find any suspects for this issue, please let me know.
I will investigate more detail situation too.

Thank you

**Comment by rizsotto** [comment]
i was using the latest released version of Bear (2.0.3) against the zlib (1.2.8) source, and could not reproduce it. (earlier versions had problems with parallel compilation, but that issue was solved in the latest release. that's why i was asking the version of Bear.)

**Comment by minhyuk** [comment]
that's weird... I tested ubuntu 12.04 64bit arch and also libear.so builded for 64 binary. is that problem? 

okay, I will have look more detail tommow! have good day~

thank you

**Comment by minhyuk** [comment]
I found why this happen.

ubuntu 12.04 use eglibc instead glibc. most recent version of ubuntu uses glibc but 12.04 didn't use that. eglibc's setenv() had crashed while <i>bear_restore_env_t</i>. 

Here is my eglibc version:
<pre>
admin@ubuntu:~/minhyuk/open_source/zlib/build$ ldd --version
ldd (Ubuntu EGLIBC 2.15-0ubuntu10.12) 2.15
...
</pre>

when replaced setenv from glibc's implementation, bear sucessful generate cdb and looks like okay.
need patch? what do you think?

Thank you

**Comment by rizsotto** [comment]
thanks for your help. i really do appreciate!
about the difference between the two libc library. it is very possible, that one implements `setenv` differently than the other. on the `devel` branch there is a new commit, which uses posix mutex to prevent concurrent modification on the environment variables. could you give it a try? thank you!

**Comment by minhyuk** [comment]
I have tried your modification, but it didn't solve problem.
I think, *bear_restore_env_t* need more lower level sync mechanism like file lock.

I add some printf in ear.c and build again, it produce like this:
<pre>
on_load (pid=17601)
in critical section bear_restore_env_t (pid=17602), (env=E7C4F110)...leave
on_load (pid=17602)
on_unload (pid=17602)
in critical section bear_restore_env_t (pid=17603), (env=E7C4F110)...leave
on_load (pid=17603)
on_unload (pid=17603)
in critical section bear_restore_env_t (pid=17604), (env=E7C4F110)...leave
on_load (pid=17604)
in critical section bear_restore_env_t (pid=17605), (env=ADAB5110)...leave
on_load (pid=17605)
in critical section bear_restore_env_t (pid=17606), (env=ADAB5110)...leave
on_load (pid=17606)
in critical section bear_restore_env_t (pid=17607), (env=63D62110)...leave
on_load (pid=17607)
in critical section bear_restore_env_t (pid=17608), (env=E1C91110)...leave
on_load (pid=17608)
on_load (pid=17609)
on_load (pid=17610)
on_unload (pid=17609)
in critical section bear_restore_env_t (pid=17611), (env=ADAB5110)...leave
on_unload (pid=17610)
on_load (pid=17611)
in critical section bear_restore_env_t (pid=17612), (env=ADAB5110)...leave
on_load (pid=17612)
in critical section bear_restore_env_t (pid=17613), (env=A2297110)...leave
in critical section bear_restore_env_t (pid=17615), (env=A2297110)...leave
in critical section bear_restore_env_t (pid=17614), (env=AF157110)...leave
on_load (pid=17615)
on_load (pid=17613)
on_load (pid=17614)
[  2%] on_unload (pid=17615)
[  5%] on_unload (pid=17613)
in critical section bear_restore_env_t (pid=17617), (env=A2297110)...leave
in critical section bear_restore_env_t (pid=17618), (env=A2297110)...leave
on_load (pid=17617)
on_load (pid=17618)
on_load (pid=17616)
Linking C static library libz.a
on_unload (pid=17616)
in critical section bear_restore_env_t (pid=17621), (env=AF157110)...leave
on_load (pid=17619)
Building C object CMakeFiles/zlib.dir/zutil.o
on_load (pid=17620)
on_unload (pid=17619)
Building C object CMakeFiles/zlib.dir/uncompr.o
on_unload (pid=17620)
in critical section bear_restore_env_t (pid=17622), (env=A2297110)...leave
in critical section bear_restore_env_t (pid=17623), (env=A2297110)...leave
on_load (pid=17622)
on_load (pid=17623)
on_load (pid=17621)
on_load (pid=17624)
on_load (pid=17625)
on_unload (pid=17621)
in critical section bear_restore_env_t (pid=17626), (env=AF157110)...leave
on_load (pid=17626)
in critical section bear_restore_env_t (pid=17627), (env=F4BB6110)...leave
on_load (pid=17627)
on_unload (pid=17627)
in critical section bear_restore_env_t (pid=17628), (env=F4BB6110)...leave
on_load (pid=17628)
on_unload (pid=17625)
on_unload (pid=17628)
on_unload (pid=17626)
in critical section bear_restore_env_t (pid=17629), (env=E4383110)...leave
in critical section bear_restore_env_t (pid=17630), (env=ADAB5110)...leave
on_load (pid=17629)
on_unload (pid=17629)
on_unload (pid=17623)
on_load (pid=17630)
[ 50%] on_unload (pid=17630)
on_unload (pid=17624)
in critical section bear_restore_env_t (pid=17631), (env=ADAB5110)...leave
in critical section bear_restore_env_t (pid=17632), (env=DADCF110)...leave
on_load (pid=17631)
Built target zlibstatic
on_load (pid=17632)
on_unload (pid=17632)
on_unload (pid=17622)
make[1]: *** [CMakeFiles/zlib.dir/all] Segmentation fault (core dumped)
make: *** [all] Error 2
</pre>

As you noticed, different process access same *env* variable, I think that is problem might happened. so process inner level sync like pthread didn't help this situation, I understand.

how about add *setenv* implementation to *libear* ?
here is my local modified version of bear(devel):
  https://github.com/minhyuk/Bear/commit/bb273c26a3ac6399548ada3b45d1dd1c0e7a497c

Thank you

**Comment by rizsotto** [comment]
thanks @minhyuk , that is interesting. the log is interesting, but since it does not shows when `fork` was called it's early to draw a conclusion that concurent processes has the same `environ` variable. (when `exec` called without `fork` it looks reasonable not create new `environ` variable.)
and i don't know how own `setenv` implementation would solve the problem? does it work for you?

**Comment by rizsotto** [comment]
i pushed a new change on `devel` branch. (overwritten the previous `mutex` attempt, so `git fetch origin && git rebase` will do the update.) it does the work as a `setenv` would, and update the `environ` variable by assignment. (hopefully that atomic like update will be less sensitive to concurrent modifications.) could you give it a try? (sorry to bother you with the testing, but since i can't reproduce it i need your help.)

**Comment by minhyuk** [comment]
yes! I just own setenv, it solve the problem...
I will check more deeply tommow, I have to know why...

**Comment by minhyuk** [comment]
here some interesting question:

http://stackoverflow.com/questions/5873029/questions-about-putenv-and-setenv

**Comment by rizsotto** [comment]
looks no longer interesting but annoying. ;) so, it looks like that _not_ using `setenv` might be a good solution. could you tried my second attempt (1d21ebd7c3174ba4bffbcf3a32945fd74c07fc8c)? does it solve the problem? i would go with that (if it works) because it does not add code but removes.

**Comment by minhyuk** [comment]
wow!! it works!! I just tested in zlib build... I will notice after more testing.

thank you!

**Comment by rizsotto** [comment]
sounds good. looking forward to hear more. :)

**Comment by minhyuk** [comment]
I am late :)
this changeset works fine.
i tested in huge opensouces testsets.

**Comment by rizsotto** [comment]
this is great, thank you for your help!
